server:
  port: 8080
  servlet:
    context-path: /myapp
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    url: jdbc:mysql://localhost:3306/noir
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update